# Generated by Django 4.1.3 on 2023-02-08 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversationmessage',
            old_name='conversations',
            new_name='conversation',
        ),
    ]
